### ISSUE TITLE
is unpaired training possible?

### ISSUE THREAD

**Issue by Orcaohoh** [eneserdo/RGB-to-IR-Translation-with-GAN#2]
Hello, I'm sorry to barge in like this, but I have a problem I hope you can help me to solve. I read your paper. And I have downloaded the FLIR dataset to train this model. But, I figured out that the result you show was paired(the rgb image and ir image you used to train is paired). The dataset I downloaded is unpaired. So I want to know that can we train this model with unpaired dataset.

**Comment by eneserdo** [comment]
Hi, thanks for your interest. The dataset in this [link](https://www.flir.com/oem/adas/adas-dataset-form/) is supposed to consist of paired data. If it is not the case somehow, still the model must be trained with paired data.
